# Change these first
owner: gcsalzburg # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: 67hours
    url: https://www.67hours.co.uk
  - name: designedbycave
    url: https://www.designedbycave.co.uk
  - name: CAVE Languages
    url: https://www.cavelanguages.co.uk
  - name: Doug Cave
    url: https://www.dougcave.co.uk
  - name: KISKA
    url: https://www.kiska.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: www.designedbycave.co.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**: open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status monitoring using Upptime.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
